### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by jgarland79** [windytan/redsea#11]
This patch fixed it for me.

diff --git a/rtl_redsea.c b/rtl_redsea.c
index 9ea1e68..2b3dca3 100644
--- a/rtl_redsea.c
+++ b/rtl_redsea.c
@@ -122,8 +122,8 @@ int main(int argc, char **argv) {
   reading_frame = 0;
   qua = 0;
   double t = 0;
-  int numsamples = 0;
 #endif
+  int numsamples = 0;
 
   while ((c = getopt (argc, argv, "f:")) != -1)
     switch (c) {

**Comment by mvglasow** [comment]
See pull request #10

**Comment by windytan** [comment]
Merged.
