### ISSUE TITLE
tmc description is missing

### ISSUE THREAD

**Issue by flux242** [windytan/redsea#26]
the following is selected: [.location,.event_codes,.description]'

result:
[12823,[243],"."]
[12823,[243],"."]
[12820,[501],"."]
[31769,[802],"."]
[61452,[401,1472],"."]
[12744,[1926],"."]
[7613,[105],"."]
[7613,[105],"."]
[32245,[802,810],"."]
[7613,[241],"."]
[7613,[241],"."]
^C

**Comment by flux242** [comment]
ah, the csv files aren't linked as resources to the executable so the cwd should contain the data folder

**Comment by windytan** [comment]
Thanks for the report, is this something I could improve on in how the repository is set up?

**Comment by flux242** [comment]
well, the csv files in the data folder could be linked to the executable. In this case it won't be necessary to have data folder in the current working directory (cwd).

**Comment by windytan** [comment]
Reopening this as a reminder.

**Comment by windytan** [comment]
fixed v0.7.3
