### ISSUE TITLE
wrong unicode symbol in the getLCDchar method

### ISSUE THREAD

**Issue by flux242** [windytan/redsea#34]
"Sie hoeren: KUNGS FEAT. JAMIE N - DON‖T YOU KNOW"

"¤" - this one seems to be also wrong. I haven't checked any further

**Comment by windytan** [comment]
Thanks. Which station is this? Do you happen to have any hex data? I'm seeing correctly decoded apostrophes from at least ANTENNE and RADIO 21.

**Comment by flux242** [comment]
the table in the getLCDchar does contain wrong symbols. The symbol before 'a' should be ` but in the table it is ‖

the 5th symbol in the table is ¤ but should be $

shouldn't they?

**Comment by windytan** [comment]
The character table is the default charset from page 74 of [the 1998 RDS specification](http://www.interactive-radio-system.com/docs/EN50067_RDS_Standard.pdf). I think this could be fixed by supporting repertoire control codes (switching character sets).

**Comment by windytan** [comment]
Or perhaps these characters could just be changed...

**Comment by flux242** [comment]
well, seems like radio stations are just using the ascii symbols codes and not the ones defined in the standard.

**Comment by windytan** [comment]
idea: A config file with per-station workaround preferences (like `"ascii_strings": true`)

**Comment by flux242** [comment]
Maybe you don't need to improve the outdated EBU tables standard at all? Just wanted to add that the symbols could be substituted by the postprocessing. I think I could do such substitutions even using jq -> split("‖") | join("`") for the specific station pi. Sorry for the 'spam' issue

**Comment by windytan** [comment]
Not spam at all, very useful discussion :) It seems the standard is applied quite liberally in different parts of the world and by different encoders.
