### ISSUE TITLE
Rename project :-)

### ISSUE THREAD

**Issue by owenson** [windytan/redsea#39]
Been looking for something like this for a couple of weeks and just stumbled across it.  Maybe call it "super RDS decoder" or similar ? :-)

**Comment by windytan** [comment]
Thanks :D I assume this is a disguised compliment? In any case, the name is admittedly not very descriptive.

**Comment by owenson** [comment]
Of course, great work just hard to find via Google :-)

**Comment by andimik** [comment]
You should at least name it ReDSea

**Comment by windytan** [comment]
I tried searching for "RDS decoder" - redsea was on the first page of DuckDuckGo results, second page in Google, and third page in Bing search.

**Comment by windytan** [comment]
Searching for "rds decoder linux" brings up redsea as the second result on the first page (US Google). Searching for "rds decoder macos" returns redsea as the first result.
