### ISSUE TITLE
Quality indicator

### ISSUE THREAD

**Issue by andimik** [windytan/redsea#42]
Is there a kind of quality indicator?

**Comment by windytan** [comment]
Not currently, no.

Perhaps it could be a per-group bit error rate estimate?

**Comment by andimik** [comment]
Well, there is already such one, it is optical, not electronic. By using -x you see lost frames (those having minuses)

But my problem is, I always write it to a sample file, so the output is redirected, not displayed.

**Comment by andimik** [comment]
Although I am not I programmer I tried to send you a PR

https://github.com/windytan/redsea/pull/43

**Comment by windytan** [comment]
With the `--ber` option you can now see an estimate of the block error rate, as a percentage of blocks containing errors during the last 12 groups.
