### ISSUE TITLE
label mismatch in event_list.h

### ISSUE THREAD

**Issue by julpapa31** [windytan/redsea#52]
Hello,

First I would like to say a very very big thank you for your work. Redsea is working like a charm. It's fully support the two commercial TMC services in my local area. 

It's seem that the line number 1062 in event_list.h should be 
 
 "1356;cold,;cold, minimum temperature (Q);F;6;L;2;;37;M6F"

instead of : 

  "1356;cold,;cold, maximum temperature (Q);F;6;L;2;;37;M6F"

About TMC encryption :  in my case they do not encrypted the location, they just send a different table code that the one expected in my country. Changing the table code in my side to the trick.

Best Regards

**Comment by windytan** [comment]
Thanks, glad to hear your report about redsea working!

Is this suggestion based on observation of actual transmissions? Note that there is already a message for "cold, minimum temperature", on line 1076. It has a different code (1401, M19F).

**Comment by julpapa31** [comment]
It's not based on observation, here the TMC providers don't broadcast any weather information.

Oups, sorry my mistake! You're definetly right, I am translating the event file, and I "cross mistmatch" the event 1401 and 1356.

**Comment by julpapa31** [comment]
So I close the issue. Thanks again to share your work.
