### ISSUE TITLE
multiple TMC location tables

### ISSUE THREAD

**Issue by veso266** [windytan/redsea#63]
Hi I was wondering if it is possible to load TMC location tables from multiple countries into redsea

I can recieve 2 public TMC services one from Slovenia and one from Italy and both carry TMC, but the one from italy of course would need italien location tables to show location corecly

I am not sure how GPS vendors do that
one scenario was when I was in Croatia and recieve RAI 1 from Italy and the car would load Italien location tables and show location from Italy that was like 200km away :smile:

**Comment by windytan** [comment]
Currently this is possible if you stop and re-start redsea with different command-line parameters. You would need to do this anyway to change the reception frequency, depending on how exactly you're using redsea.

Each location table has a country code and location table number, and a receiver should be able to tell whether it has the correct table for a TMC service or not.

**Comment by veso266** [comment]
I am using redsea in a C# app feeding it RDS data with HEX so when tuning SDR# rds data changes so I do not need to restart redsea, not sure how would I feed multiple location tables in it?

**Comment by windytan** [comment]
In that case it's not possible as of yet, but sounds like it could very well be implemented.
