### ISSUE TITLE
Missing --channels option in wiki

### ISSUE THREAD

**Issue by andimik** [windytan/redsea#67]
On https://github.com/windytan/redsea/wiki/Input-formats you are mentioning `--channels` but it is not described in https://github.com/windytan/redsea/wiki/Command-line-options (only in https://github.com/windytan/redsea/blob/master/src/redsea.cc )

Could you explain what is the use case? Left channel one frequency, right channel another?

How to record such a file (with `rtl_fm` for example)?

**Comment by windytan** [comment]
Thanks, Ive updated the wiki.

A redsea user had a specific use case where they wanted to decode multiple interleaved channels simultaneously, which is why I implemented this niche feature on request. There's no such option in rtl_fm to my knowledge.
