### ISSUE TITLE
Unknown warnings category 'experimental::smartmatch' at ./redsea.pl line 13

### ISSUE THREAD

**Issue by pclov3r** [windytan/redsea#7]
Perl v5.14.2

Get this error when trying to run it. If I comment out line 13 it starts fine however there is zero output even for very strong FM stations w/RDS. In programs like SDR# the RDS subcarrier is very viable.

**Comment by windytan** [comment]
Fixed (hopefully) by using  use experimental qw(smartmatch);

**Comment by windytan** [comment]
Subcarrier detection is difficult and will probably be improved on later.
