### ISSUE TITLE
Decoder Identification bits are the wrong way around

### ISSUE THREAD

**Issue by Zipdox2** [windytan/redsea#86]
The Decoder Identification bits are the wrong way around. The RDS specification says that the most significant bit (d3) gets transmitted first (Dynamic PTY). This corresponds to segment address 0. Your code interprets this as the stereo bit.
![image](https://user-images.githubusercontent.com/121819828/215005250-9d0fd9bd-156e-4175-b193-1a73a97820e6.png)
![image](https://user-images.githubusercontent.com/121819828/215005395-21daa8ca-caf0-4d30-ad0f-92b8214bba38.png)

**Comment by windytan** [comment]
You're right, thanks a lot for the fix!
