### ISSUE TITLE
Possible length off-by-one in RadioText+ decode

### ISSUE THREAD

**Issue by nivex** [windytan/redsea#9]
Looks like RadioText+ might be dropping the last character. I'm inferring this from the standard RT messages preceeding it:
```
17EF  2A TP:0 PTY:10 RT:'B93.9 Close Your Eyes Parmalee ↵                                ' RT_OK
  RadioText+: 
    Item running
    Tag item.artist: Parmale
    Tag item.title: Close Your Eye
```

**Comment by windytan** [comment]
Thanks, this is actually the first time I see any output from the RT+ decoder, I've been writing it blind without test data.

**Comment by windytan** [comment]
It's indeed length + 1 in the spec, fixed now.
