### ISSUE TITLE
`partial_alt_kilohertz` missing in Wiki

### ISSUE THREAD

**Issue by andimik** [windytan/redsea#91]
Although `partial_alt_kilohertz` was introduced five years ago,

https://github.com/windytan/redsea/blob/b34fd7ce72516d94407957a7fdb3e0e8eef751df/CHANGES.md?plain=1#L84

it's still not mentioned in the Wiki.

https://github.com/windytan/redsea/wiki/Supported-RDS-features

**Comment by windytan** [comment]
Thanks, I've actually opened wiki editing now
